# Generated by Django 2.0 on 2020-01-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20200118_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='police',
            new_name='police_count',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='health_info',
            field=models.TextField(default='Health@gmail.com', max_length=3000),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police_info',
            field=models.TextField(default='police@info.com', max_length=3000),
        ),
    ]
