# Generated by Django 2.0 on 2020-01-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
    ]
